import { StyleSheet } from 'react-native';

const offWhite = "#f3f2f8";

export default StyleSheet.create({
    container: {
      flex: 1,
      alignItems: "center",
      marginTop: 0,
      paddingRight: 0,
      maxWidth: 5000,
      backgroundColor: "#FFFF",
    },
    gradient: {
      flex: 1,
      width: "100%",
      paddingLeft: 0,
      paddingRight: 0,
      borderRadius: 0,
    },
  
    aboveTitle: {
      fontSize: 23,
      position: "absolute",
      top: "40%",
      left: "10%",
      fontWeight: "400",
      color: "white",
    },
    title: {
      fontSize: 43,
      fontWeight: "bold",
      position: "absolute",
      paddingLeft: 30,
      top: "55%",
      left: "1%",
      color: "white",
    },
    description: {
      textAlign: "center",
      marginBottom: 18,
      fontWeight: "200",
  
      color: "green",
    },
  
    leftBar: {
      backgroundColor: offWhite,
      position: "absolute",
      left: "0%",
      top: "15%",
      width: 25,
      height: "100%",
      borderRadius: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    rightBar: {
      backgroundColor: offWhite,
      position: "absolute",
      right: "0%",
      top: "15%",
      width: 25,
      height: "100%",
      borderRadius: 0,
      alignItems: "center",
      justifyContent: "center",
    },
    scheduleArea: {
      marginBottom: "20%",
      backgroundColor: "white",
    },
    timeArea: {
      marginBottom: "75%",
    },
    lunchArea: {
      paddingBottom: 280,
      paddingTop: 0,
      alignItems: "center",
      justifyContent: "center",
    },
  
    periodName: {
      fontSize: 32,
      fontWeight: "600",
      color: "#384050",
  
      alignItems: "center",
      justifyContent: "center",
  
      marginRight: "15%",
      marginLeft: "12.5%",
    },
    classTime: {
      fontSize: 26,
      fontWeight: "400",
      color: "#384050",
      alignItems: "center",
      justifyContent: "center",
      marginRight: "10%",
      marginLeft: "12%",
    },
    lunchTitle: {
      fontSize: 32,
      fontWeight: "600",
      textTransform: "capitalize",
      color: "#384050",
      marginRight: "10%",
      marginLeft: "5%",
      marginTop: "5%",
    },
    lunchItems: {
      fontSize: 26,
      fontWeight: "400",
      color: "#384050",
      alignItems: "center",
      justifyContent: "center",
      marginRight: "5%",
      marginLeft: "5%",
    },
    linearGradient: {
      flex: 1,
      paddingLeft: 15,
      paddingRight: 15,
      borderRadius: 5,
    },
    button: {
      fontFamily: "Gill Sans",
      textAlign: "center",
      justifyContent: "center",
      alignItems: "center",
      color: "#ffffff",
      backgroundColor: "transparent",
      width: 90,
      height: 60,
    },
    centerButton: {
      paddingTop: 20,
      paddingLeft: 40,
      paddingRight: 40,
    },
    footer: {
      flex: 1,
      flexDirection: "row",
      alignItems: "baseline",
      justifyContent: "center",
      position: "absolute",
      marginTop: "196%",
      marginLeft: 0,
      paddingRight: 0,
      width: "100%",
      height: 100,
      backgroundColor: "#FFFF",
      borderTopColor: offWhite,
      borderTopWidth: 2,
    },
    settingsTitle: {
      fontSize: 20,
      fontWeight: "bold",
      top: "55%",
      textAlign: "center",
      color: "white",
    },
    settingsBackButton: {
      fontSize: 35,
      fontWeight: "bold",
      color: "white",
    },
    noSchoolText: {
      color: "#384050",
      fontSize: 35,
      fontWeight: "bold",
      paddingTop: 10,
    },
  });